### ISSUE TITLE
Er moeten kwaleitseisen voor de code komen.

### ISSUE THREAD

**Issue by mPlagge** [Gewad/Project4Bankalicious#9]
Bijlage A:
"Voor de kwaliteit van de code zijn eisen opgesteld, zoals leesbaarheid, gebruik van programmeerparadigma’s, performance, onderhoudbaarheid etc.
De projectgroep stelt een document op met daarin de kwaliteitseisen waaraan de code moet voldoen."

Kan je alle kwaliteitseizen aub in kwatiteitseisen/kwalitietseisen_teamdeel/file of iets vergelijkbaars zetten?

**Comment by boaskalma** [comment]
eerste paar er bij gezet alleen nog wat mager.

**Comment by boaskalma** [comment]
done
